In [201]:

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [202]:
data  = pd.read_csv('/kaggle/input/digit-recognizer/train.csv')

In [203]:
data =  np.array(data)
m,n = data.shape
np.random.shuffle(data)#so that when we seperate the data randomly as the set may be arranged and may not be trained for that particu


In [204]:
data = np.array(data)
m, n = data.shape
np.random.shuffle(data) # shuffle before splitting into dev and training sets

data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev / 255.

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255.
_,m_train = X_train.shape

In [205]:
def init_params():
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(0,Z)

def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A

def forward_prop(W1,b1,W2,b2,X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1,A1,Z2,A2

def one_hot(y):
    one_hot_y = np.zeros((y.size,y.max()+1))
    one_hot_y[np.arange(y.size),y] = 1
    return one_hot_y.T

def deri(Z):
    return Z>0
    
def back_prop(Z1,A1,Z2,A2,W1,W2,X,Y):
    m = X.shape[1]
    one_hot_y = one_hot(Y)
    dz2 = A2 - one_hot_y
    dw2 = 1/m * dz2.dot(A1.T)
    db2 = 1/m * np.sum(dz2)
    dz1 = W2.T.dot(dz2) * deri(Z1)
    dw1 = 1/m * dz1.dot(X.T)
    db1 = 1/m * np.sum(dz1)
     
    return dw1,db1,dw2,db2

def update_params(W1,b1,W2,b2,dw1,db1,dw2,db2,alpha):
    W1 = W1 - alpha*dw1
    W2 = W2 - alpha*dw2
    b1 = b1 - alpha*db1
    b2 = b2 - alpha*db2
    return W1,W2,b1,b2

In [206]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = back_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, W2, b1, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2

W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 0.10, 500)


Iteration:  0
[6 6 1 ... 6 6 6] [4 6 1 ... 0 9 8]
0.11885365853658536
Iteration:  10
[5 5 5 ... 9 5 5] [4 6 1 ... 0 9 8]
0.2290487804878049
Iteration:  20
[5 6 7 ... 0 5 6] [4 6 1 ... 0 9 8]
0.3224878048780488
Iteration:  30
[5 6 1 ... 0 5 6] [4 6 1 ... 0 9 8]
0.38341463414634147
Iteration:  40
[6 6 1 ... 0 5 6] [4 6 1 ... 0 9 8]
0.4265121951219512
Iteration:  50
[6 6 1 ... 0 4 6] [4 6 1 ... 0 9 8]
0.4647317073170732
Iteration:  60
[6 6 1 ... 0 4 6] [4 6 1 ... 0 9 8]
0.4976341463414634
Iteration:  70
[5 6 1 ... 0 4 6] [4 6 1 ... 0 9 8]
0.5239756097560976
Iteration:  80
[7 6 1 ... 0 4 6] [4 6 1 ... 0 9 8]
0.5494878048780488
Iteration:  90
[7 6 1 ... 0 4 6] [4 6 1 ... 0 9 8]
0.5737317073170731
Iteration:  100
[7 6 1 ... 0 4 6] [4 6 1 ... 0 9 8]
0.5954634146341463
Iteration:  110
[7 6 1 ... 0 4 6] [4 6 1 ... 0 9 8]
0.6160975609756097
Iteration:  120
[7 6 1 ... 0 4 6] [4 6 1 ... 0 9 8]
0.6357073170731707
Iteration:  130
[7 6 1 ... 0 4 6] [4 6 1 ... 0 9 8]
0.653609756097561
Iteration:  140
